[package]
name = "stack-allocator"
version = "0.1.1"
edition = "2021"
authors = ["Khashayar Fereidani"]
description = "A stack-based memory allocator with optional fallback to a global/secondary allocator."
license = "MIT"
repository = "https://github.com/fereidani/stack-allocator"
readme = "README.md"
keywords = ["allocator", "stack", "alloc", "memory-management", "no-std"]
categories = ["data-structures", "no-std"]

[dependencies]
allocator-api2 = { version = "0.2.9", default-features = false, features = [
    "alloc",
] }

[build-dependencies]
rustc_version = "0.4"

[features]
std = []
alloc = []

[dev-dependencies]
# intentional so when it breaks in CI we notice(allocator-api2 upgrade)
hashbrown = "0"
